# Generated by Django 5.2 on 2025-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB')], max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=10)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_connection_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
