# Generated by Django 5.2 on 2025-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='last_connection_attempt',
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('sqlite', 'SQLite'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB')], max_length=20),
        ),
    ]
