# Generated by Django 5.2 on 2025-05-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connections', '0002_remove_databaseconnection_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='last_connection_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('sqlite', 'SQLite'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB')], max_length=20),
        ),
    ]
